version: '3.9'
services:
  database:
    image: postgres:16.3
    container_name: database
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=webshop
    env_file:
      - ./docker/.env
    networks:
      - mynet


  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - POSTGRES_JDBC_URL=jdbc:postgresql://database:5432/webshop
    env_file:
      - ./docker/.env
    ports:
      - '8081:8080'
    depends_on:
      - database
    networks:
      - mynet

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - BACKEND=backend:8080
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - mynet

volumes:
  postgres_data:
    driver: local

networks:
  mynet:
    driver: bridge