version: '3.9'
services:
  node:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    env_file:
      - ./docker/.env
    ports:
      - '3000:3000'
    expose:
      - '5173'
    depends_on:
      - kotlin
    networks:
      - mynet

  kotlin:
    build:
      dockerfile: Dockerfile
    container_name: kotlin-backend
    env_file:
      - ./docker/.env
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - mynet


  postgres:
    image: postgres:16.3
    container_name: postgres-database
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./docker/.env
    networks:
      - mynet

volumes:
  postgres_data:
    driver: local

networks:
  mynet:
    driver: bridge