version: '3.9'

services:
  db:
    container_name: webshop-db
    image: postgres:16.3
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

    env_file:
      - .env
volumes:
  postgres_data: